name: Validate Renovate Config
on:
  pull_request:
    paths:
      - 'renovate.json'
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: docker.io/renovate/renovate:44.45@sha256:5ab76d9ffdd885d6dad7bd2aa9ae40242d3906c17c45f681425956b5950b42f7
      options: --user 0:0
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate-config-validator
