name: Validate Renovate Config
on:
  pull_request:
    paths:
      - 'renovate.json'
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: docker.io/renovate/renovate:44.96@sha256:b5b12953e3e7eae05e0e1921b7efdae34d81e7000f63b8dbf9356a83b7c9a357
      options: --user 0:0
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate-config-validator
