name: Validate Renovate Config
on:
  pull_request:
    paths:
      - 'renovate.json'
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: docker.io/renovate/renovate:44.51@sha256:dd5a8ca92b2f3cbb8e3c8de35c63ae46494b074463c5e2488ed43e128b22f32e
      options: --user 0:0
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate-config-validator
